### ISSUE TITLE
deleteAll() doesn't do anything if you don't pass any arguments

### ISSUE THREAD

**Issue by graemetait** [burriko/cakephp-faker-fixtures#2]
FYI @mdhInfoeSec

**Comment by mattdharmon** [comment]
Ahh, thank you. I'm still pretty new to cakephp and the project I am working on is in CakePHP2. If I pass it an empty array, will that work, or do I need to put something in it like Model.id > 0?

**Comment by graemetait** [comment]
I think it would need to be something like this `deleteAll(['1 = 1'])`. Just an SQL condition that'll select everything. Shame there isn't just a truncate() method in Cake, as that would be much faster!

**Comment by mattdharmon** [comment]
So I am thinking of something like `$model->deleteAll(["{$modelName}.id IS NOT NULL"]);`. Hows that work?
